In [1]:
import numpy as np 
import pandas as pd

Finding Missing data

In [4]:
data={
    'A':[1,2,np.nan,4,5], 
    'B':[np.nan,2,3,4,5], 
    'C':[1,2,3,np.nan,np.nan], 
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [7]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
#Filling missing values

df